# .github/workflows/deploy.yml
name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install & Build
        run: |
          npm ci
          npm run build
      
      - name: Deploy with rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan www.cybersecai.cloud >> ~/.ssh/known_hosts
          rsync -avz --delete dist/ userweb@www.cybersecai.cloud:/home/userweb/webroot



